version: "3.3"

services:
  traefik:
    image: "traefik:v3.3"
    container_name: "traefik"
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  ks-app:
    env_file: ".env"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    image: ${IMAGE_URI}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.test_app.rule=Host(`${APP_HOST}`)"
      - "traefik.http.routers.test_app.entrypoints=web"
      - "traefik.http.services.myservice.loadbalancer.server.port=${APP_PORT}"